src/Entity/AskLogin.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface ;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AskLoginRepository")
 * @UniqueEntity(
 * fields={"email"},
 * message="This email already exists."
 * )
 */
class AskLogin implements UserInterface
{
    public static $status_demand   = 1;
    public static $status_accepted = 2;
    public static $status_refused  = 3;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Lastname field cannot be empty")
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     * @Assert\NotBlank
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="8", minMessage="At least 8 char")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Passwords must be the same")
     */
    private $confirmPassword;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $project;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $grpdConsentAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status;
    
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $processedAt;


    public function __construct()
    {
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getConfirmPassword()
    {
        return $this->confirmPassword;
    }
    
    public function setConfirmPassword(string $confirmPassword): self
    {
        $this->confirmPassword = $confirmPassword;
        return $this;
    }
    
    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials(){}
        
    public function getSalt(){}
    
    public function getRoles(){
        return array('ROLE_USER');
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getProcessedAt(): ?\DateTimeInterface
    {
        return $this->processedAt;
    }

    public function setProcessedAt(?\DateTimeInterface $processedAt): self
    {
        $this->processedAt = $processedAt;

        return $this;
    }

    public function getProject()
    {
        return $this->project;
    }

    public function setProject(string $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getFullname(){
        return $this->firstname." ".$this->lastname;
    }

    public function getGrpdConsentAt(): ?\DateTimeInterface
    {
        return $this->grpdConsentAt;
    }

    public function setGrpdConsentAt(\DateTimeInterface $grpdConsentAt): self
    {
        $this->grpdConsentAt = $grpdConsentAt;

        return $this;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Language.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LanguageRepository")
 */
class Language
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=3, nullable=true)
     */
    private $iso639_3;

    /**
     * @ORM\Column(type="string", length=3, nullable=true)
     */
    private $iso639_2;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label_en;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $label_fr;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIso6393(): ?string
    {
        return $this->iso639_3;
    }

    public function setIso6393(?string $iso639_3): self
    {
        $this->iso639_3 = $iso639_3;

        return $this;
    }

    public function getIso6392(): ?string
    {
        return $this->iso639_2;
    }

    public function setIso6392(?string $iso639_2): self
    {
        $this->iso639_2 = $iso639_2;

        return $this;
    }

    public function getLabelEn(): ?string
    {
        return $this->label_en;
    }

    public function setLabelEn(string $label_en): self
    {
        $this->label_en = $label_en;

        return $this;
    }

    public function getLabelFr(): ?string
    {
        return $this->label_fr;
    }

    public function setLabelFr(?string $label_fr): self
    {
        $this->label_fr = $label_fr;

        return $this;
    }
}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Form\PersonType;
use App\Form\Person1Type;
use App\Form\PersonRoleType;
use App\Repository\PersonRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @IsGranted("ROLE_ADMIN")
 * @Route("/person")
 */
class PersonController extends AbstractController
{
    /**
     * @Route("/", name="person_index", methods="GET")
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(PersonRepository $personRepository): Response
    {
        return $this->render('person/index.html.twig', ['people' => $personRepository->findAll()]);
    }

    /**
     * @Route("/new", name="person_new", methods="GET|POST")
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $person = new Person();
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($person);
            $em->flush();

            return $this->redirectToRoute('person_index');
        }

        return $this->render('person/new.html.twig', [
            'person' => $person,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="person_show", methods="GET")
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Person $person): Response
    {
        return $this->render('person/show.html.twig', ['person' => $person]);
    }

    /**
     * @Route("/{id}/edit", name="person_edit", methods="GET|POST")
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Person $person): Response
    {
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('person_index', ['id' => $person->getId()]);
        }

        return $this->render('person/edit.html.twig', [
            'person' => $person,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/role", name="person_role", methods="GET|POST")
     * @IsGranted("ROLE_ADMIN")
     */
    public function manage_role(Request $request, Person $person): Response
    {
        $form = $this->createForm(PersonRoleType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($person);
            $em->flush();
            return $this->redirectToRoute('person_index');
        }

        return $this->render('person/edit.html.twig', [
            'person' => $person,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}", name="person_delete", methods="DELETE")
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Person $person): Response
    {
        if ($this->isCsrfTokenValid('delete'.$person->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($person);
            $em->flush();
        }

        return $this->redirectToRoute('person_index');
    }
}

templates/person/_delete_form.html.twig
<form method="post" action="{{ path('person_delete', {'id': person.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ person.id) }}">
    <button class="btn">Delete</button>
</form>

templates/person/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/person/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Person{% endblock %}

{% block body %}
    <h1>Edit Person</h1>
	<h3>{{ person.fullname }}</h3>
	
    {{ include('person/_form.html.twig', {'button_label': 'Save'}) }}

    <a href="{{ path('person_index') }}">back to list</a>

{% endblock %}

templates/person/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Person index{% endblock %}

{% block body %}
    <h1>Person index</h1>

    <table class="table" id="datatable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Lastname</th>
                <th>Firstname</th>
                <th>Email</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for person in people %}
            <tr>
                <td>{{ person.id }}</td>
                <td>{{ person.lastname }}</td>
                <td>{{ person.firstname }}</td>
                <td><a href="mailto:{{ person.email }}">{{ person.email }}</a></td>
                <td>
                    {% if 'ROLE_ADMIN' in person.roles %}
                        <i class="fas fa-jedi danger"></i> admin
                    {% endif %}

                </td>  
                {#<td>
                    {% for project in person.projects %}
                        <a href="{{path('field_show',{'id':project.mainField.id})}}"><span class="badge badge-pill badge-success">{{project.mainField.labelEn}}</span></a>
                    {% endfor %}

                </td>
                #}        
                <td>
                    <div class="btn-group" role="group">
                        <a class="btn btn-primary" href="{{ path('person_show', {'id': person.id}) }}" data-toggle="tooltip" title="See profile"><i class="fas fa-info-circle"></i></a>
                        <a class="btn btn-primary" href="{{ path('person_edit', {'id': person.id}) }}" data-toggle="tooltip" title="Edit profile"><i class="fas fa-user-edit"></i></a>
                        <a class="btn btn-secondary" href="{{ path('reset_user_password', {'id': person.id}) }}" data-toggle="tooltip" title="Reset password and send email"><i class="fas fa-key"></i></a>

                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('person_new') }}"><i class="fas fa-plus-circle"></i> Create new</a>
{% endblock %}

templates/person/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Person{% endblock %}

{% block body %}
    <h1>Create new Person</h1>

    {{ include('person/_form.html.twig') }}

    <a href="{{ path('person_index') }}">back to list</a>
{% endblock %}

templates/person/personalInformation.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Personnal Informations</h1>
   {% if not app.user.person %}
       Welcome here. To apply for a call, you need to fill these information :
    {% endif%}
    {{form_start(form)}}
    {{form_row(form.lastname, {'label':'Lastname',
                            'attr':{
                                'placeholder':'Same as written on you passport'
                                }
                            })}}
    {{form_row(form.firstname, {'label':'Firstname',
                            'attr':{
                                'placeholder':'Same as written on you passport'
                                }
                            })}}
    {{form_row(form.usualLastname, {'label':'Usual lastname',
                            'attr':{
                                'placeholder':'If different only'
                                }
                            })}}
    {{form_row(form.usualFirstname, {'label':'Usual firstname',
                            'attr':{
                                'placeholder':'If different only'
                                }
                            })}}
    {{form_row(form.gender, {'label':'Gender',
                            'attr':{
                                'placeholder':'1 or 2'
                                }
                            })}}
    {{form_row(form.dateOfBirth, {'label':'Date of birth',
                            'attr':{
                                'placeholder':'MM/DD/YYYY format'
                                }
                            })}}
    {{form_row(form.placeOfBirth, {'label':'Place of birth',
                            'attr':{
                                'placeholder':'City / Country'
                                }
                            })}}

                            
    <button type="submit" class="btn btn-success"><i class="fas fa-check"></i></button>
    {{form_end(form)}}
{% endblock %}

templates/person/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Person{% endblock %}

{% block body %}
    <h1>Person</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ person.id }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ person.lastname }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ person.firstname }}</td>
            </tr>
            <tr>
                <th>UsualLastname</th>
                <td>{{ person.usualLastname }}</td>
            </tr>
            <tr>
                <th>UsualFirstname</th>
                <td>{{ person.usualFirstname }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ person.gender }}</td>
            </tr>
            <tr>
                <th>DateOfBirth</th>
                <td>{{ person.dateOfBirth ? person.dateOfBirth|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>PlaceOfBirth</th>
                <td>{{ person.placeOfBirth }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ person.email }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ person.password }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ person.createdAt ? person.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>VerifiedEmailAt</th>
                <td>{{ person.verifiedEmailAt ? person.verifiedEmailAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('person_index') }}">back to list</a>

    <a href="{{ path('person_edit', {'id': person.id}) }}">edit</a>

    {{ include('person/_delete_form.html.twig') }}
{% endblock %}