src/Entity/Call.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CallRepository")
 * @ORM\Table(name="call_app")
 */
class Call
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max="255")
     */
    private $labelFr;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptionFr;
    
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max="255")
     */
    private $labelEn;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptionEn;
    /**
     * @ORM\Column(type="datetime")
     */
    private $openingDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $closingDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ScientificCouncil", inversedBy="calls")
     * @ORM\JoinColumn(nullable=false)
     */
    private $scientificCouncil;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ApplicationForm", mappedBy="call")
     */
    private $applicationForms;

    public function __construct()
    {
        $this->applicationForms = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabelFr(): ?string
    {
        return $this->labelFr;
    }

    public function setLabelFr(string $labelFr): self
    {
        $this->labelFr = $labelFr;

        return $this;
    }

    public function getDescriptionFr(): ?string
    {
        return $this->descriptionFr;
    }

    public function setDescriptionFR(?string $descriptionFr): self
    {
        $this->descriptionFr = $descriptionFr;

        return $this;
    }
    public function getLabelEn(): ?string
    {
        return $this->labelEn;
    }

    public function setLabelEn(string $labelEn): self
    {
        $this->labelEn = $labelEn;

        return $this;
    }

    public function getDescriptionEn(): ?string
    {
        return $this->descriptionEn;
    }

    public function setDescriptionEn(?string $descriptionEn): self
    {
        $this->descriptionEn = $descriptionEn;

        return $this;
    }
    public function getOpeningDate(): ?\DateTimeInterface
    {
        return $this->openingDate;
    }

    public function setOpeningDate(\DateTimeInterface $openingDate): self
    {
        $this->openingDate = $openingDate;

        return $this;
    }

    public function getClosingDate(): ?\DateTimeInterface
    {
        return $this->closingDate;
    }

    public function setClosingDate(\DateTimeInterface $closingDate): self
    {
        $this->closingDate = $closingDate;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getScientificCouncil(): ?ScientificCouncil
    {
        return $this->scientificCouncil;
    }

    public function setScientificCouncil(?ScientificCouncil $scientificCouncil): self
    {
        $this->scientificCouncil = $scientificCouncil;

        return $this;
    }
    
    public function getIsOpen()
    {
        $today = new \DateTime;
        if($this->openingDate < $today && $this->closingDate > $today){
            return true;
        }else{
            return false;
        }
        
    }


    /**
     * @return Collection|ApplicationForm[]
     */
    public function getApplicationForms(): Collection
    {
        return $this->applicationForms;
    }

    public function addApplicationForm(ApplicationForm $applicationForm): self
    {
        if (!$this->applicationForms->contains($applicationForm)) {
            $this->applicationForms[] = $applicationForm;
            $applicationForm->setCall($this);
        }

        return $this;
    }

    public function removeApplicationForm(ApplicationForm $applicationForm): self
    {
        if ($this->applicationForms->contains($applicationForm)) {
            $this->applicationForms->removeElement($applicationForm);
            // set the owning side to null (unless already changed)
            if ($applicationForm->getCall() === $this) {
                $applicationForm->setCall(null);
            }
        }

        return $this;
    }
    /**
     * Return application if person given in parameter is a candidate. Return null othewise
     * @param Person $person
     * @return ApplicationForm
     */
    public function isCandidate(Person $person)
    {
        foreach ($this->applicationForms as $application) {
            if($application->getProject()->getPerson() === $person){
                return $application;
            }
        }
        return null;
    }

    public function getSubmittedApplications(){
   
        $submittedApplicationForms = $this->applicationForms->filter(function ($item) {
            return ($item->getSubmittedAt() !== null);
        });
        return $submittedApplicationForms;
    }
    public function getUnsubmittedApplications(){
   
        $unsubmittedApplicationForms = $this->applicationForms->filter(function ($item) {
            return ($item->getSubmittedAt() === null);
        });
        return $unsubmittedApplicationForms;
    }
}

src/Entity/ScientificCouncil.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ScientificCouncilRepository")
 */
class ScientificCouncil
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max="255")
     */
    private $label;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Call", mappedBy="scientificCouncil")
     */
    private $calls;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Person", mappedBy="scientificCouncils")
     */
    private $members;

    public function __construct()
    {
        $this->calls = new ArrayCollection();
        $this->members = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection|Call[]
     */
    public function getCalls(): Collection
    {
        return $this->calls;
    }

    public function addCall(Call $call): self
    {
        if (!$this->calls->contains($call)) {
            $this->calls[] = $call;
            $call->setScientificCouncil($this);
        }

        return $this;
    }

    public function removeCall(Call $call): self
    {
        if ($this->calls->contains($call)) {
            $this->calls->removeElement($call);
            // set the owning side to null (unless already changed)
            if ($call->getScientificCouncil() === $this) {
                $call->setScientificCouncil(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Person[]
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addPerson(Person $person): self
    {
        if (!$this->members->contains($person)) {
            $this->members[] = $person;
            $person->addScientificCouncil($this);
        }

        return $this;
    }

    public function removePerson(Person $person): self
    {
        if ($this->members->contains($person)) {
            $this->members->removeElement($person);
            $person->removeScientificCouncil($this);
        }

        return $this;
    }
}

src/Form/ScientificCouncilType.php
<?php

namespace App\Form;

use App\Entity\ScientificCouncil;
use App\Form\CallFromCouncilType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class ScientificCouncilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label')
            ->add('description')
            ->add(
                'date', 
                DateType::class, 
                array(
                    'label'=>'Date',
                    // renders it as a single text box
                    'required'=> false,
                    'widget' => 'single_text',
                    'html5' => false,
                    'help' => 'Date format is yyyy-mm-dd',
                    'attr'=>array(
                        'class'=> 'datepicker',
                        'placeholder'=>'yyyy-mm-dd',
                    )
                )
            )
            ->add(
                'calls',
                CollectionType::class,
                array(
                    'entry_type' => CallFromCouncilType::class,
                    'allow_add' => true,
                )
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ScientificCouncil::class,
        ]);
    }
}

src/Controller/ScientificCouncilController.php
<?php

namespace App\Controller;

use App\Entity\ScientificCouncil;
use App\Form\ScientificCouncilType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\ScientificCouncilRepository;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/scientific/council")
 * @Route("CS")
 */
class ScientificCouncilController extends AbstractController
{
    /**
     * @Route("/", name="scientific_council_index", methods="GET")
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(ScientificCouncilRepository $scientificCouncilRepository): Response
    {
        return $this->render('scientific_council/index.html.twig', ['scientific_councils' => $scientificCouncilRepository->findAll()]);
    }

    /**
     * @Route("/new", name="scientific_council_new", methods="GET|POST")
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $scientificCouncil = new ScientificCouncil();
        $form = $this->createForm(ScientificCouncilType::class, $scientificCouncil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            foreach($scientificCouncil->getCalls() as $call){
                $call->setScientificCouncil($scientificCouncil);
                $em->persist($call);
            }
            $em->persist($scientificCouncil);
            $em->flush();

            return $this->redirectToRoute('scientific_council_index');
        }

        return $this->render('scientific_council/new.html.twig', [
            'scientific_council' => $scientificCouncil,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="scientific_council_show", methods="GET")
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(ScientificCouncil $scientificCouncil): Response
    {
        return $this->render('scientific_council/show.html.twig', ['scientific_council' => $scientificCouncil]);
    }

    /**
     * @Route("/{id}/edit", name="scientific_council_edit", methods="GET|POST")
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, ScientificCouncil $scientificCouncil): Response
    {
        $form = $this->createForm(ScientificCouncilType::class, $scientificCouncil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('scientific_council_index', ['id' => $scientificCouncil->getId()]);
        }

        return $this->render('scientific_council/edit.html.twig', [
            'scientific_council' => $scientificCouncil,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="scientific_council_delete", methods="DELETE")
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, ScientificCouncil $scientificCouncil): Response
    {
        if ($this->isCsrfTokenValid('delete'.$scientificCouncil->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($scientificCouncil);
            $em->flush();
        }

        return $this->redirectToRoute('scientific_council_index');
    }
}

templates/scientific_council/_delete_form.html.twig
<form method="post" action="{{ path('scientific_council_delete', {'id': scientific_council.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ scientific_council.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/scientific_council/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/scientific_council/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ScientificCouncil{% endblock %}
{% form_theme form _self %}
{% block body %}
    <h1>Edit ScientificCouncil</h1>
    <a href="{{ path('scientific_council_index') }}">back to list</a>

    {{ include('scientific_council/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('scientific_council/_delete_form.html.twig') }}
{% endblock %}

{% block _scientific_council_calls_widget %}
    Add some calls :
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" class="btn btn-primary" id="add-call">Add a call</button>
    </div>
{% endblock %}  

{% block _scientific_council_calls_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _scientific_council_calls_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-11">
                <div class="row mt-2">
                    <div class="col">
                        {{ form_widget(form.labelFr) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.labelEn) }}
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col">
                        {{ form_widget(form.descriptionFr) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.descriptionEn) }}
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col">
                        {{ form_widget(form.openingDate) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.closingDate) }}
                    </div>
                </div>
            </div>
            <div class="col-1">
                <div class="row mt-2" data-toggle="tooltip" data-placement="bottom" title="You can't delete an existing call">
                    <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger" disabled >X</button>
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $('#add-call').click(function(){
            const index = +$('#widgets-counter').val();
            const tmpl = $('#scientific_council_calls').data('prototype').replace(/__name__/g, index);
            
            $('#scientific_council_calls').append(tmpl);
            $('#widgets-counter').val(index + 1)
            //Delete button
            handleDeleteButton();
            //Datepicker
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd'
            });
        })
        function handleDeleteButton(){
            $('button[data-action="delete"]').click(function(){
                const target = this.dataset.target;
                $(target).remove();
            })
        }
    handleDeleteButton();
    </script>

{% endblock %}

templates/scientific_council/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ScientificCouncil index{% endblock %}

{% block body %}
    <h1>Scientific Council list</h1>

    <table class="table" id="datatable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Label</th>
                <th>Description</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for scientific_council in scientific_councils|sort|reverse %}
            <tr>
                <td>{{ scientific_council.id }}</td>
                <td>{{ scientific_council.label }}</td>
                <td>{{ scientific_council.description[:70] }}</td>
                <td>{{ scientific_council.date ? scientific_council.date|date('Y-m-d') : '' }}</td>
                <td>
                    <div class="btn-group" role="group">
                        <a class="btn btn-success" href="{{ path('scientific_council_show', {'id': scientific_council.id}) }}" data-toggle="tooltip" title="See scientific council"><i class="fas fa-info-circle"></i></a>
                        <a class="btn btn-warning" href="{{ path('scientific_council_edit', {'id': scientific_council.id}) }}" data-toggle="tooltip" title="Edit scientific council"><i class="fas fa-edit"></i></a>
                    </div>
                   
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary" href="{{ path('scientific_council_new') }}"><i class="fas fa-plus-circle"></i> Create new</a>
{% endblock %}

templates/scientific_council/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ScientificCouncil{% endblock %}
{% form_theme form _self %}
{% block body %}
    <h1>Create new ScientificCouncil</h1>

    {{ include('scientific_council/_form.html.twig') }}

    <a href="{{ path('scientific_council_index') }}">back to list</a>
{% endblock %}

{% block _scientific_council_calls_widget %}
    Add some calls :
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" class="btn btn-primary" id="add-call">Add a call</button>
    </div>
{% endblock %}  

{% block _scientific_council_calls_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _scientific_council_calls_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-11">
                <div class="row mt-2">
                    <div class="col">
                        {{ form_widget(form.labelFr) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.labelEn) }}
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col">
                        {{ form_widget(form.descriptionFr) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.descriptionEn) }}
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col">
                        {{ form_widget(form.openingDate) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.closingDate) }}
                    </div>
                </div>
            </div>
            <div class="col-1">
                <div class="row mt-2">
                    <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $('#add-call').click(function(){
            const index = +$('#widgets-counter').val();
            const tmpl = $('#scientific_council_calls').data('prototype').replace(/__name__/g, index);
            
            $('#scientific_council_calls').append(tmpl);
            $('#widgets-counter').val(index + 1)
            //Delete button
            handleDeleteButton();
            //Datepicker
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd'
            });
        })
        function handleDeleteButton(){
            $('button[data-action="delete"]').click(function(){
                const target = this.dataset.target;
                $(target).remove();
            })
        }
    handleDeleteButton();
    </script>

{% endblock %}

templates/scientific_council/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ScientificCouncil{% endblock %}

{% block body %}
    <h1>{{ scientific_council.label }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ scientific_council.id }}</td>
            </tr>
            <tr>
                <th>Label</th>
                <td>{{ scientific_council.label }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ scientific_council.description }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ scientific_council.date ? scientific_council.date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <a class="btn btn-warning" href="{{ path('scientific_council_edit', {'id': scientific_council.id}) }}" data-toggle="tooltip" title="Edit this Scientific council"><i class="fas fa-edit"></i></a>

    <h2>Calls</h2>
    
    <table class="table" id="datatable">
        <thead>
            <tr>
                <th>Label Fr</th>
                <th>Opening Date</th>
                <th>Closing Date</th>
                <th>Scientific council</th>
                <th>Status</th>
                <th>number of candidates</th>
                <th>actions</th>

            </tr>
        </thead>
        <tbody>
        {% for call in scientific_council.calls %}
            <tr>
                <td>{{ call.labelFr }}</td>
                <td>{{ call.openingDate ? call.openingDate|date('Y-m-d') : '' }}</td>
                <td>{{ call.closingDate ? call.closingDate|date('Y-m-d') : '' }}</td>
                <td><a href="{{path('scientific_council_show', {'id': call.scientificCouncil.id})}}">{{ call.scientificCouncil.label}}</a></td>
                {% if call.isOpen %}
                    <td><span class="badge badge-pill badge-success">Ongoing</span></td>
                {% else %}
                    <td><span class="badge badge-pill badge-dark">Closed</span></td>
                {% endif %}
                <td>
                    <a href="{{ path('call_show', {'id': call.id}) }}" class="h4" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="See application forms"><span class="badge badge-pill badge-primary" >{{ call.applicationForms|length }}</span></a>
                </td>
                <td>
                    <div class="btn-group" role="group">
                        <a class="btn btn-success" href="{{ path('call_show', {'id': call.id}) }}" data-toggle="tooltip" title="See call"><i class="fas fa-info-circle"></i></a>
                        <a class="btn btn-warning" href="{{ path('call_edit', {'id': call.id}) }}" data-toggle="tooltip" title="Edit call"><i class="fas fa-edit"></i></a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-outline-primary" href="{{ path('scientific_council_index') }}"><i class="fas fa-list-ul"></i> back to list</a>

{% endblock %}